services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - api_network
  backend:
    container_name: backend
    build: ./src/
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    depends_on:
      - db
    restart: always
    networks:
      - api_network

  db:
    image: docker.io/bitnami/postgresql:15
    container_name: db
    ports:
      - "5434:5432"
    env_file:
      - ./src/.env
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
volumes:
  db_data:
  
